// Point class 
class Point {
  
  // initializes point with x, y, and z coordinates 
  // and confidence of prediction
  constructor(x, y, confidence) {
    this.x = x;
    this.y = y;
    
    // variable to determine the amount of interpolation between colors
    this.amt = random(confidence);
    
  }
  
  // renders points to canvas
  draw() {
    
    // interpolating colors generated by coordinates
    let color1 = colorPicker1.color()
    let color2 = colorPicker2.color()
    let interColor = lerpColor(color1, color2, this.amt);
    
    // drawing the points to the canvas
    strokeWeight(2);
    stroke(interColor);
    if (renderMode == 1) {
      point(this.x,this.y);
    }
    else {
      fill(interColor);
      curveVertex(this.x,this.y);
    }
    
  }
}